/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.ucdsl.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.xtext.example.ucdsl.services.UcDslGrammarAccess
import uc.UCModel

class UcDslFormatter extends AbstractFormatter2 {
	
	@Inject extension UcDslGrammarAccess

	def dispatch void format(UCModel uCModel, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (useCase : uCModel.usecase) {
			useCase.format
		}
		for (actor : uCModel.actor) {
			actor.format
		}
	}
	
}
