/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.ucdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UcDslUiModule extends AbstractUcDslUiModule {

	public UcDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
