/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.ucdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UcDslStandaloneSetup extends UcDslStandaloneSetupGenerated {

	public static void doSetup() {
		new UcDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
