/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.reqdsl.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.xtext.example.reqdsl.services.ReqDslGrammarAccess
import req.ReqModel

class ReqDslFormatter extends AbstractFormatter2 {
	 
	@Inject extension ReqDslGrammarAccess

	def dispatch void format(ReqModel reqModel, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (requirement : reqModel.requirement) {
			requirement.format
		}
	}
	
}
