/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.ucdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.ucdsl.UcDslRuntimeModule;
import org.xtext.example.ucdsl.UcDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UcDslIdeSetup extends UcDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UcDslRuntimeModule(), new UcDslIdeModule()));
	}
	
}
