/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.ucdsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class UcDslScopeProvider extends AbstractUcDslScopeProvider {

}
