/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.reqdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ReqDslUiModule extends AbstractReqDslUiModule {

	public ReqDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
