/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.ucdsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class UcDslProposalProvider extends AbstractUcDslProposalProvider {
}
