/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.reqdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.reqdsl.ReqDslRuntimeModule;
import org.xtext.example.reqdsl.ReqDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ReqDslIdeSetup extends ReqDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ReqDslRuntimeModule(), new ReqDslIdeModule()));
	}
	
}
