/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.reqdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReqDslRuntimeModule extends AbstractReqDslRuntimeModule {
}
