/*
 * generated by Xtext 2.43.0
 */
package org.xtext.example.reqdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ReqDslStandaloneSetup extends ReqDslStandaloneSetupGenerated {

	public static void doSetup() {
		new ReqDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
